# Generated by Django 5.0.3 on 2024-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientLogo',
            field=models.ImageField(default='default_logo.jpg', upload_to='company_logos'),
        ),
    ]
