# Generated by Django 5.0.3 on 2024-03-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_customer_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
