# Generated by Django 5.0.3 on 2024-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
