# Generated by Django 5.0.3 on 2024-03-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='14 days', null=True),
        ),
    ]
